### ISSUE TITLE
leapp upgrade command failing when selinux is disabled

### ISSUE THREAD

**Issue by varunmylaraiah** [oamg/leapp-repository#39] opened 2019-01-11 13:05 UTC
**Actual behavior**
leapp upgrade command failing when selinux is disabled

**To Reproduce**
Steps to reproduce the behavior
1. Disable SELinux
2. run "leapp upgrade"

**Expected behavior**
leap upgrade command should work without any Traceback

**System information (please complete the following information):**
 - OS and version: (e.g. Fedora 29 or `$ cat /etc/system-release`)
Red Hat Enterprise Linux Server release 7.6 (Maipo)
 - `# uname -a`
Linux qe-blade-14.testrelm1001.test 3.10.0-957.el7.x86_64 #1 SMP Thu Oct 4 20:48:51 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
 - `# rpm -qa "*leapp*"` 
python2-leapp-0.4.0-1.201901110920Z.a3beb13.master.el7_5.noarch
leapp-0.4.0-1.201901110920Z.a3beb13.master.el7_5.noarch
leapp-repository-0.4.0-0.201901111130Z.0be0a79.remove_test_repo.PR38.el7_5.noarch
leapp-repository-data-0.4.0-0.201901111130Z.0be0a79.remove_test_repo.PR38.el7_5.noarch

****

**Additional context**
Console Output
- `# leapp upgrade`
2019-01-11 07:36:43.462 INFO     PID: 1833 leapp: Logging has been initialized
2019-01-11 07:36:43.595 INFO     PID: 1833 leapp.repository.common: A new repository 'common' is initialized at /etc/leapp/repos.d/common
2019-01-11 07:36:43.721 INFO     PID: 1833 leapp.repository.system_upgrade_el7toel8: A new repository 'system_upgrade_el7toel8' is initialized at /etc/leapp/repos.d/system_upgrade/el7toel8
2019-01-11 07:36:44.256 INFO     PID: 1833 leapp.workflow: Starting workflow execution: InplaceUpgrade - ID: d6b52ce8-75cc-4193-89c3-2f4613b2c301
2019-01-11 07:36:44.404 INFO     PID: 1833 leapp.workflow: Starting phase Facts collection
2019-01-11 07:36:44.529 INFO     PID: 1833 leapp.workflow.Facts collection: Starting stage Before of phase Facts collection
2019-01-11 07:36:44.779 INFO     PID: 1833 leapp.workflow.Facts collection: Starting stage Main of phase Facts collection
2019-01-11 07:36:44.904 INFO     PID: 1833 leapp.workflow.Facts collection: Executing actor transaction_workarounds 
2019-01-11 07:36:45.321 INFO     PID: 1833 leapp.workflow.Facts collection: Executing actor rpm_scanner 
2019-01-11 07:36:47.746 INFO     PID: 1833 leapp.workflow.Facts collection: Executing actor rpm_transaction_config_tasks_collector 
2019-01-11 07:36:48.188 INFO     PID: 1833 leapp.workflow.Facts collection: Executing actor os_release_collector 
2019-01-11 07:36:48.613 INFO     PID: 1833 leapp.workflow.Facts collection: Executing actor red_hat_signed_rpm_scanner 
2019-01-11 07:36:49.339 INFO     PID: 1833 leapp.workflow.Facts collection: Executing actor system_facts 
2019-01-11 07:36:49.677 WARNING  PID: 2076 leapp.workflow.Facts collection.system_facts: Unable to read parameter "hotmod" of kernel module "ipmi_si"
Process Process-41:
Traceback (most recent call last):
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/repository/actor_definition.py", line 59, in _do_run
    target_actor(logger=logger, messaging=messaging).run(*args, **kwargs)
  File "/usr/lib/python2.7/site-packages/leapp/actors/__init__.py", line 129, in run
    self.process(*args)
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/systemfacts/actor.py", line 21, in process
    selinux=systemfacts.get_selinux_status(),
  File "/usr/share/leapp-repository/repositories/system_upgrade/el7toel8/actors/systemfacts/libraries/systemfacts.py", line 227, in get_selinux_status
    return SELinux(**outdata)
  File "/usr/lib/python2.7/site-packages/leapp/models/__init__.py", line 86, in __init__
    getattr(defined_fields[field], init_method)(kwargs, field, self)
  File "/usr/lib/python2.7/site-packages/leapp/models/fields/__init__.py", line 110, in from_initialization
    self._validate_model_value(value=source_value, name=name)
  File "/usr/lib/python2.7/site-packages/leapp/models/fields/__init__.py", line 166, in _validate_model_value
    super(BuiltinField, self)._validate_model_value(value, name)
  File "/usr/lib/python2.7/site-packages/leapp/models/fields/__init__.py", line 62, in _validate_model_value
    raise ModelViolationError('The value of "{name}" field is None, but this is not allowed'.format(name=name))
ModelViolationError: The value of "policy" field is None, but this is not allowed

**Comment by radomil** [comment] 2019-02-14 17:08
This issue has been fixed by above mentioned PR #27 merge and tests were covered by PR #56 merge.

**Closed by radomil** 2019-02-14 17:08 UTC
Labels: bug

**Comment by petermaloney** [comment] 2024-09-09 14:44
FYI this can also be caused by syntax errors in the `/etc/yum.repos.d/*.repo` files

**Comment by pirat89** [comment] 2024-09-10 04:15
> FYI this or similar error message can also be caused by syntax errors in the `/etc/yum.repos.d/*.repo` files

similar traceback can be seen in number other situations when system is broken. in short, it's ok as system is required to be fully working / correctly configured. but we plan to improve the error msg in this one particular case, to print info what yum/dnf repo file is invalid.
