### ISSUE TITLE
no kernel-devel package should be left before running leapp.

### ISSUE THREAD

**Issue by winndows** [oamg/leapp-repository#651] opened 2021-03-12 06:16 UTC
**Actual behavior**

It says we can leave one kernel-devel before running leapp, but it will report following error with kernel-devel.

kernel-devel depends on perl, but perl will be replaced with perl-interpretor on rhel8.

======snip=======
dnf_package_download
Message: DNF execution failed with non zero exit code.
...................
...................
Error: transaction check vs depsolve:
**perl is needed by (installed) kernel-devel-xxxxxx86_64**
To diagnose the problem, try running: 'rpm -Va --nofiles --nodigest'.
You probably have corrupted RPMDB, running 'rpm --rebuilddb' might fix the issue.
======snip=======

**To Reproduce**
run "leapp upgrade" with one kernel-devel rpm installed.

**Expected behavior**
no errors happens

**Comment by Rezney** [comment] 2021-03-12 11:14
Hi @winndows In this case I would recommend opening a support case with Red Hat. Thanks...

**Comment by pirat89** [comment] 2021-03-12 11:35
As well, we are not able to reproduce your issue. I tried the upgrade right now regarding your instructions and everything work as expected. So far, I do not see any issue in this repository.
```
# rpm -qa | grep kernel
kernel-devel-3.10.0-1160.21.1.el7.x86_64
kernel-3.10.0-957.27.2.el7.x86_64
kernel-3.10.0-1127.el7.x86_64
kernel-tools-libs-3.10.0-1160.21.1.el7.x86_64
kernel-tools-3.10.0-1160.21.1.el7.x86_64
kernel-3.10.0-1160.21.1.el7.x86_64
# rpm -q perl
perl-5.16.3-299.el7_9.x86_64
# leapp upgrade --debug
....

============================================================
                           REPORT                           
============================================================

A report has been generated at /var/log/leapp/leapp-report.json
A report has been generated at /var/log/leapp/leapp-report.txt

============================================================
                       END OF REPORT                        
============================================================

```

Closing the issue as there is nothing for us to do. As well, problems with specific rpms could point to problems that should be fixed in specific rpms.

**Closed by pirat89** 2021-03-12 11:35 UTC
Labels: bug
